# Generated by Django 6.0.2 on 2026-04-29 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_documento', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Aprendiz',
                'verbose_name_plural': 'Aprendices',
                'ordering': ['apellidos', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CentroFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Centro de Formación',
                'verbose_name_plural': 'Centros de Formación',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='FaseProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Fase del Proyecto',
                'verbose_name_plural': 'Fases del Proyecto',
                'ordering': ['ficha', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Regional',
                'verbose_name_plural': 'Regionales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('competencias', models.JSONField(default=list, help_text='Lista de textos de competencias relacionadas')),
                ('resultados', models.JSONField(default=list, help_text='Lista de textos de resultados de aprendizaje relacionados')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='reportes.faseproyecto')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['fase', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha_reporte', models.DateField(blank=True, null=True)),
                ('ficha_caracterizacion', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('denominacion', models.TextField(blank=True, null=True)),
                ('estado_ficha', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('modalidad', models.CharField(blank=True, max_length=255, null=True)),
                ('centro_formacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fichas', to='reportes.centroformacion')),
                ('regional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fichas', to='reportes.regional')),
            ],
            options={
                'verbose_name': 'Ficha de Caracterización',
                'verbose_name_plural': 'Fichas de Caracterización',
                'ordering': ['-fecha_reporte'],
            },
        ),
        migrations.AddField(
            model_name='faseproyecto',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='reportes.ficha'),
        ),
        migrations.CreateModel(
            name='JuicioEvaluativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('competencia', models.TextField(blank=True, null=True)),
                ('resultado_aprendizaje', models.TextField(blank=True, null=True)),
                ('juicio_evaluacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_hora_juicio', models.DateTimeField(blank=True, null=True)),
                ('funcionario', models.CharField(blank=True, max_length=255, null=True)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='juicios', to='reportes.aprendiz')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juicios', to='reportes.ficha')),
            ],
            options={
                'verbose_name': 'Juicio Evaluativo',
                'verbose_name_plural': 'Juicios Evaluativos',
                'ordering': ['-fecha_hora_juicio'],
            },
        ),
        migrations.AddField(
            model_name='centroformacion',
            name='regional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='centros_formacion', to='reportes.regional'),
        ),
        migrations.AlterUniqueTogether(
            name='faseproyecto',
            unique_together={('ficha', 'orden')},
        ),
    ]
