# Generated by Django 6.0.2 on 2026-04-29 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CentroFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='reportes.aprendiz')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='reportes.competencia')),
            ],
        ),
        migrations.CreateModel(
            name='Formacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficha', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('denominacion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_ficha', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_inicio', models.TimeField(blank=True, null=True)),
                ('fecha_fin', models.TimeField(blank=True, null=True)),
                ('modalidad', models.CharField(blank=True, max_length=255, null=True)),
                ('id_centro_formacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formaciones', to='reportes.centroformacion')),
            ],
        ),
        migrations.AddField(
            model_name='centroformacion',
            name='regional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centros', to='reportes.regional'),
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='reportes.competencia')),
            ],
        ),
        migrations.CreateModel(
            name='JuicioEvaluativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juicios', to='reportes.aprendiz')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juicios', to='reportes.instructor')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juicios', to='reportes.resultado')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(blank=True, choices=[('DNI', 'DNI'), ('PAS', 'Pasaporte')], max_length=255, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=255, null=True)),
                ('formacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='reportes.formacion')),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='reportes.usuario'),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aprendiz', to='reportes.usuario'),
        ),
    ]
